version: 2

seeds:
  - name: departments
    description: "Departments"
    tags: [seed, bronze]
    meta:
      source_file: "raw_departments.csv"
    config: 
      delimiter: ","
    columns:
      - name: DEPARTMENT_ID
        tests:
          - unique
          - not_null
