CREATE USER faktury identified by oracle;
GRANT CONNECT, RESOURCE TO faktury;
alter user faktury quota UNLIMITED on users;
alter session set current_schema = faktury;


CREATE TABLE FAKTURY (
    FA_ID NUMBER(10) PRIMARY KEY,
    FA_NUMER VARCHAR2(10 BYTE) NOT NULL,
    FA_DATA_WYSTAWIENIA DATE NOT NULL,
    FA_OPIS VARCHAR2(64 BYTE),
    FA_KOD_KLIENTA NUMBER(10)
);

CREATE TABLE TOWARY (
    TOW_ID NUMBER(10) PRIMARY KEY,
    TOW_NAZWA VARCHAR2(50 BYTE) NOT NULL,
    TOW_CENA NUMBER(10),
    TOW_PODATEK NUMBER(3),
    TOW_JAKOSC VARCHAR2(5 BYTE)
);

CREATE TABLE POZYCJE_FAKTUR (
    PF_ID NUMBER(10) PRIMARY KEY,
    PF_LP NUMBER(10) NOT NULL,
    PF_ILOSC NUMBER(10) NOT NULL,
    PF_FA_ID NUMBER(10) NOT NULL,
    PF_TOW_ID NUMBER(10) NOT NULL,
    CONSTRAINT PF_FA_ID_FK FOREIGN KEY (PF_FA_ID) REFERENCES FAKTURY(FA_ID),
    CONSTRAINT PF_TOW_ID_FK FOREIGN KEY (PF_TOW_ID) REFERENCES TOWARY(TOW_ID)
);

CREATE INDEX PF_FA_ID_IDX ON POZYCJE_FAKTUR(PF_FA_ID);
CREATE INDEX PF_TOW_ID_IDX ON POZYCJE_FAKTUR(PF_TOW_ID);
