version: 2

sources:
  - name: raw 
    schema: hr_dwh 
    tables:
      - name: raw_departments
        description: "Table loaded from a CSV file with department data. The data was incorrect or messy and required cleaning."    
models:
  - name: departments__update
    description: "Fixes some known data issues, like wrong or missing values."

  - name: departments__trimmed
    description: "Removes extra spaces from text fields."

  - name: departments__cast
    description: "Converts column types."

  - name: departments__deduplicated
    description: "Removes duplicate records based on department ID."

  - name: departments__final
    description: "Clean and final version of department data."
    columns:
      - name: DEPARTMENT_ID
        description: "Unique ID for each department."
        tests: 
          - unique
          - not_null
      - name: DEPARTMENT_NAME
        description: "Name of the department."
        tests:
          - not_null
      - name: LOCATION_ID
        description: "ID of the location where the department is based."
        tests:
          - not_null